# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfc312822d6f4baca38b1dd34fed1d1e9cc62048ff0d25690d82513588df2d11cf62e9931cfb2d2611da92f4686406dd0db382b0985c7465713effb88fcb8c2c

test:
  secret_key_base: bf147a1581a01879ab16fb219ef0b0e0ad835f0f6b549217c2adcbee304ed35764b6d0d82c62879cb7c27fe5a1c81aab4c3c68be6192347a5e1acd5f835ba232

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
